#!/usr/bin/env python3
"""Fidelity check for the generated Taylor-2 word data.

`FQFP/BCH/QuinticTaylor2.lean` is generated by `scripts/gen_bch_quintic_taylor2.py`, which derives
the degree-5 BCH word list itself (noncommutative polynomials in `a`, `b`) and then applies the
`V`-substitutions. This script checks that derivation against the *source's* emitted answer: it
parses the explicit `(n / 720 : 𝕂) • (x * ... * y)` chains of

  * `bch_quintic_term_lin_diff`   (Lean-BCH/BCH/Basic.lean:3028)
  * `bch_quintic_term_taylor2_remainder_{2V,3V,4V}`   (Basic.lean:3243, 3319, 3355)
  * `bch_quintic_term_taylor2_remainder`   (Basic.lean:3107)

and compares them, as multisets of (word pattern, numerator over 720), against the generated
`bchQuinticTerm*Words` / `bchQuinticTerm*Coeffs` vectors. It also checks the V-count split, which is
what the bound constant depends on.

Run with:  python artifacts/bch-audit-round-one/_check_taylor2_words.py
"""

import pathlib
import re
import sys

SRC = pathlib.Path(r"D:\project\Lean-BCH\BCH\Basic.lean")
TGT = pathlib.Path(r"D:\project\CQM1\FQFP\BCH\QuinticTaylor2.lean")

LETTER = {"x": 0, "V": 1, "y": 2}
TERM = re.compile(r"\(\s*(-?\d+)\s*/\s*720\s*:\s*𝕂\s*\)\s*•\s*\(([^)]*)\)")


def source_terms(text, name):
    body = text.split(f"def {name} ", 1)[1].split("\n\n", 1)[0]
    body = body.split(":=", 1)[1]
    out = []
    for num, word in TERM.findall(body):
        letters = [tok.strip() for tok in word.split("*")]
        assert all(t in LETTER for t in letters), letters
        out.append((tuple(LETTER[t] for t in letters), int(num)))
    return out


def target_data(text, words_name, coeffs_name):
    words_body = text.split(f"def {words_name} ", 1)[1].split("\n\n", 1)[0]
    patterns = re.findall(r"\[([^][]*)\]", words_body.split(":=", 1)[1])
    coeffs_body = text.split(f"def {coeffs_name} ", 1)[1].split("\n\n", 1)[0]
    coeffs = re.findall(r"-?\d+", coeffs_body.split(":=", 1)[1])
    assert len(patterns) == len(coeffs), (len(patterns), len(coeffs))
    words = [tuple(int(t) for t in p.split(",")) for p in patterns]
    return list(zip(words, [int(c) for c in coeffs]))


def check(label, want, got):
    if sorted(want) == sorted(got):
        print(f"MATCH {label}: {len(got)} terms")
        return True
    only_src = sorted(set(want) - set(got))
    only_tgt = sorted(set(got) - set(want))
    print(f"MISMATCH {label}: {len(want)} vs {len(got)} terms")
    print(f"  only in source ({len(only_src)}): {only_src[:5]}")
    print(f"  only in target ({len(only_tgt)}): {only_tgt[:5]}")
    return False


def main():
    src = SRC.read_text(encoding="utf-8")
    tgt = TGT.read_text(encoding="utf-8")
    ok = True

    ok &= check("lin_diff",
                source_terms(src, "bch_quintic_term_lin_diff"),
                target_data(tgt, "bchQuinticTermLinDiffWords", "bchQuinticTermLinDiffCoeffs"))

    combined = []
    for k in (2, 3, 4):
        want = source_terms(src, f"bch_quintic_term_taylor2_remainder_{k}V")
        got = target_data(tgt, f"bchQuinticTermTaylor2Remainder{k}VWords",
                          f"bchQuinticTermTaylor2Remainder{k}VCoeffs")
        ok &= check(f"remainder_{k}V", want, got)
        # the split must also be by V-count
        bad = [w for w, _ in got if w.count(1) != k]
        if bad:
            print(f"MISMATCH remainder_{k}V: words with the wrong V-count: {bad[:3]}")
            ok = False
        combined += got

    ok &= check("taylor2_remainder (sum of the three pieces)",
                source_terms(src, "bch_quintic_term_taylor2_remainder"),
                combined)

    print("all Taylor-2 word data matches the source" if ok else "FIDELITY FAILURE")
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
