/-
Copyright (c) 2026 Foresight Quantum. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Foresight Quantum
-/
module

public import FQFP.BCH.BCHTerms

/-!
# The Taylor expansion of the degree-5 term

`bchQuinticTerm (x + V) y - bchQuinticTerm x y` splits into its directional derivative
(`bchQuinticTerm_lin_diff`, linear in `V`) and a second-order remainder, and the remainder splits
further by the number of `V` letters (`bchQuinticTerm_taylor2_remainder_{2V,3V,4V}`).

The remainder is *defined* as the sum of those three pieces, so the split identity is `rfl`, and
each piece has a uniform letter profile: every word of the `kV` piece has exactly `k` letters `V`
and `5 - k` letters from `{x, y}`. That uniformity is what lets the bound constant come out as the
source's `(1680 + 720 + 30)/720 = 2430/720`.

## Provenance

Generated by `scripts/gen_bch_quintic_taylor2.py`, which ports the word lists of
`Lean-BCH/scripts/gen_bch_quintic_term_taylor2.py`. That script emits the same words as explicit
`+`-chains and then proves the norm bound one monomial at a time (`Basic.lean:3461-4830`, about
1200 lines, including 2V/3V/4V bound lemmas that nothing outside `Basic.lean` uses). Here the words
are data and each definition is a `∑` over `wordProdList`, which the arity-free norm API bounds in
a single application.

**Assisted by Deepseek Harness**
-/

@[expose] public section

namespace FQFP.BCH

noncomputable section

/-! ### Word data

Patterns are `List (Fin 3)`: `0` is `x`, `1` is `V`, `2` is `y`. Coefficients are numerators over
`720`, matching `BCHTerms.norm_sevenTwenty_rat` (`‖(720 : ℚ)‖ = 720`). -/

/-- The 75 word patterns of `bchQuinticTerm_lin_diff`: one `V` at each `x`-position. -/
def bchQuinticTermLinDiffWords : Fin 75 → List (Fin 3) :=
  ![[0, 0, 0, 1, 2], [0, 0, 0, 2, 1], [0, 0, 1, 0, 2], [0, 0, 1, 2, 0], [0, 0, 1, 2, 2],
    [0, 0, 2, 0, 1], [0, 0, 2, 1, 0], [0, 0, 2, 1, 2], [0, 0, 2, 2, 1], [0, 1, 0, 0, 2],
    [0, 1, 0, 2, 0], [0, 1, 0, 2, 2], [0, 1, 2, 0, 0], [0, 1, 2, 0, 2], [0, 1, 2, 2, 0],
    [0, 1, 2, 2, 2], [0, 2, 0, 0, 1], [0, 2, 0, 1, 0], [0, 2, 0, 1, 2], [0, 2, 0, 2, 1],
    [0, 2, 1, 0, 0], [0, 2, 1, 0, 2], [0, 2, 1, 2, 0], [0, 2, 1, 2, 2], [0, 2, 2, 0, 1],
    [0, 2, 2, 1, 0], [0, 2, 2, 1, 2], [0, 2, 2, 2, 1], [1, 0, 0, 0, 2], [1, 0, 0, 2, 0],
    [1, 0, 0, 2, 2], [1, 0, 2, 0, 0], [1, 0, 2, 0, 2], [1, 0, 2, 2, 0], [1, 0, 2, 2, 2],
    [1, 2, 0, 0, 0], [1, 2, 0, 0, 2], [1, 2, 0, 2, 0], [1, 2, 0, 2, 2], [1, 2, 2, 0, 0],
    [1, 2, 2, 0, 2], [1, 2, 2, 2, 0], [1, 2, 2, 2, 2], [2, 0, 0, 0, 1], [2, 0, 0, 1, 0],
    [2, 0, 0, 1, 2], [2, 0, 0, 2, 1], [2, 0, 1, 0, 0], [2, 0, 1, 0, 2], [2, 0, 1, 2, 0],
    [2, 0, 1, 2, 2], [2, 0, 2, 0, 1], [2, 0, 2, 1, 0], [2, 0, 2, 1, 2], [2, 0, 2, 2, 1],
    [2, 1, 0, 0, 0], [2, 1, 0, 0, 2], [2, 1, 0, 2, 0], [2, 1, 0, 2, 2], [2, 1, 2, 0, 0],
    [2, 1, 2, 0, 2], [2, 1, 2, 2, 0], [2, 1, 2, 2, 2], [2, 2, 0, 0, 1], [2, 2, 0, 1, 0],
    [2, 2, 0, 1, 2], [2, 2, 0, 2, 1], [2, 2, 1, 0, 0], [2, 2, 1, 0, 2], [2, 2, 1, 2, 0],
    [2, 2, 1, 2, 2], [2, 2, 2, 0, 1], [2, 2, 2, 1, 0], [2, 2, 2, 1, 2], [2, 2, 2, 2, 1]]

/-- The coefficients of `bchQuinticTerm_lin_diff`, over `720`. -/
def bchQuinticTermLinDiffCoeffs : Fin 75 → ℤ :=
  ![-1, 4, -1, 4, 4, -6, -6, -6, -6, -1, 4, 4, -6, -6, -6, 4, 4, 4, -6, 24, 4, -6, 24, -6, -6,
    -6, -6, 4, -1, 4, 4, -6, -6, -6, 4, 4, -6, 24, -6, -6, -6, 4, -1, -1, -1, 4, -6, -1, 4, -6,
    -6, -6, -6, 24, -6, -1, 4, -6, -6, -6, 24, -6, 4, 4, 4, -6, -6, 4, -6, -6, -6, 4, 4, 4, -1]

/-- The 70 word patterns of the `2V` piece, exactly `2` letters `V`. -/
def bchQuinticTermTaylor2Remainder2VWords : Fin 70 → List (Fin 3) :=
  ![[0, 0, 1, 1, 2], [0, 0, 1, 2, 1], [0, 0, 2, 1, 1], [0, 1, 0, 1, 2], [0, 1, 0, 2, 1],
    [0, 1, 1, 0, 2], [0, 1, 1, 2, 0], [0, 1, 1, 2, 2], [0, 1, 2, 0, 1], [0, 1, 2, 1, 0],
    [0, 1, 2, 1, 2], [0, 1, 2, 2, 1], [0, 2, 0, 1, 1], [0, 2, 1, 0, 1], [0, 2, 1, 1, 0],
    [0, 2, 1, 1, 2], [0, 2, 1, 2, 1], [0, 2, 2, 1, 1], [1, 0, 0, 1, 2], [1, 0, 0, 2, 1],
    [1, 0, 1, 0, 2], [1, 0, 1, 2, 0], [1, 0, 1, 2, 2], [1, 0, 2, 0, 1], [1, 0, 2, 1, 0],
    [1, 0, 2, 1, 2], [1, 0, 2, 2, 1], [1, 1, 0, 0, 2], [1, 1, 0, 2, 0], [1, 1, 0, 2, 2],
    [1, 1, 2, 0, 0], [1, 1, 2, 0, 2], [1, 1, 2, 2, 0], [1, 1, 2, 2, 2], [1, 2, 0, 0, 1],
    [1, 2, 0, 1, 0], [1, 2, 0, 1, 2], [1, 2, 0, 2, 1], [1, 2, 1, 0, 0], [1, 2, 1, 0, 2],
    [1, 2, 1, 2, 0], [1, 2, 1, 2, 2], [1, 2, 2, 0, 1], [1, 2, 2, 1, 0], [1, 2, 2, 1, 2],
    [1, 2, 2, 2, 1], [2, 0, 0, 1, 1], [2, 0, 1, 0, 1], [2, 0, 1, 1, 0], [2, 0, 1, 1, 2],
    [2, 0, 1, 2, 1], [2, 0, 2, 1, 1], [2, 1, 0, 0, 1], [2, 1, 0, 1, 0], [2, 1, 0, 1, 2],
    [2, 1, 0, 2, 1], [2, 1, 1, 0, 0], [2, 1, 1, 0, 2], [2, 1, 1, 2, 0], [2, 1, 1, 2, 2],
    [2, 1, 2, 0, 1], [2, 1, 2, 1, 0], [2, 1, 2, 1, 2], [2, 1, 2, 2, 1], [2, 2, 0, 1, 1],
    [2, 2, 1, 0, 1], [2, 2, 1, 1, 0], [2, 2, 1, 1, 2], [2, 2, 1, 2, 1], [2, 2, 2, 1, 1]]

/-- The coefficients of the `2V` piece, over `720`. -/
def bchQuinticTermTaylor2Remainder2VCoeffs : Fin 70 → ℤ :=
  ![-1, 4, -6, -1, 4, -1, 4, 4, -6, -6, -6, -6, 4, 4, 4, -6, 24, -6, -1, 4, -1, 4, 4, -6, -6,
    -6, -6, -1, 4, 4, -6, -6, -6, 4, 4, 4, -6, 24, 4, -6, 24, -6, -6, -6, -6, 4, -1, -1, -1, 4,
    -6, -6, -1, -1, 4, -6, -1, 4, -6, -6, -6, -6, 24, -6, 4, 4, 4, -6, -6, 4]

/-- The 30 word patterns of the `3V` piece, exactly `3` letters `V`. -/
def bchQuinticTermTaylor2Remainder3VWords : Fin 30 → List (Fin 3) :=
  ![[0, 1, 1, 1, 2], [0, 1, 1, 2, 1], [0, 1, 2, 1, 1], [0, 2, 1, 1, 1], [1, 0, 1, 1, 2],
    [1, 0, 1, 2, 1], [1, 0, 2, 1, 1], [1, 1, 0, 1, 2], [1, 1, 0, 2, 1], [1, 1, 1, 0, 2],
    [1, 1, 1, 2, 0], [1, 1, 1, 2, 2], [1, 1, 2, 0, 1], [1, 1, 2, 1, 0], [1, 1, 2, 1, 2],
    [1, 1, 2, 2, 1], [1, 2, 0, 1, 1], [1, 2, 1, 0, 1], [1, 2, 1, 1, 0], [1, 2, 1, 1, 2],
    [1, 2, 1, 2, 1], [1, 2, 2, 1, 1], [2, 0, 1, 1, 1], [2, 1, 0, 1, 1], [2, 1, 1, 0, 1],
    [2, 1, 1, 1, 0], [2, 1, 1, 1, 2], [2, 1, 1, 2, 1], [2, 1, 2, 1, 1], [2, 2, 1, 1, 1]]

/-- The coefficients of the `3V` piece, over `720`. -/
def bchQuinticTermTaylor2Remainder3VCoeffs : Fin 30 → ℤ :=
  ![-1, 4, -6, 4, -1, 4, -6, -1, 4, -1, 4, 4, -6, -6, -6, -6, 4, 4, 4, -6, 24, -6, -1, -1, -1,
    -1, 4, -6, -6, 4]

/-- The 5 word patterns of the `4V` piece, exactly `4` letters `V`. -/
def bchQuinticTermTaylor2Remainder4VWords : Fin 5 → List (Fin 3) :=
  ![[1, 1, 1, 1, 2], [1, 1, 1, 2, 1], [1, 1, 2, 1, 1], [1, 2, 1, 1, 1], [2, 1, 1, 1, 1]]

/-- The coefficients of the `4V` piece, over `720`. -/
def bchQuinticTermTaylor2Remainder4VCoeffs : Fin 5 → ℤ :=
  ![-1, 4, -6, 4, -1]

/-! ### The definitions -/

/-- The weighted sum of the words named by `words` with the numerators `coeffs`, over `720`. -/
noncomputable def bchWordSum {𝔸 : Type*} [Ring 𝔸] [SMul ℚ 𝔸] {m : ℕ}
    (coeffs : Fin m → ℤ) (words : Fin m → List (Fin 3)) (x V y : 𝔸) : 𝔸 :=
  (720 : ℚ)⁻¹ • ∑ i, (coeffs i : ℚ) • wordProdList ![x, V, y] (words i)

/-- **First-order directional difference** of `bchQuinticTerm` in its first argument: one `V` at
each `x`-position of each degree-5 word. -/
noncomputable def bchQuinticTermLinDiff {𝔸 : Type*} [Ring 𝔸] [SMul ℚ 𝔸] (x V y : 𝔸) : 𝔸 :=
  bchWordSum bchQuinticTermLinDiffCoeffs bchQuinticTermLinDiffWords x V y

/-- The `2V` piece of the second-order Taylor remainder: exactly two letters `V`. -/
noncomputable def bchQuinticTermTaylor2Remainder2V {𝔸 : Type*} [Ring 𝔸] [SMul ℚ 𝔸]
    (x V y : 𝔸) : 𝔸 :=
  bchWordSum bchQuinticTermTaylor2Remainder2VCoeffs bchQuinticTermTaylor2Remainder2VWords x V y

/-- The `3V` piece of the second-order Taylor remainder: exactly three letters `V`. -/
noncomputable def bchQuinticTermTaylor2Remainder3V {𝔸 : Type*} [Ring 𝔸] [SMul ℚ 𝔸]
    (x V y : 𝔸) : 𝔸 :=
  bchWordSum bchQuinticTermTaylor2Remainder3VCoeffs bchQuinticTermTaylor2Remainder3VWords x V y

/-- The `4V` piece of the second-order Taylor remainder: exactly four letters `V`. -/
noncomputable def bchQuinticTermTaylor2Remainder4V {𝔸 : Type*} [Ring 𝔸] [SMul ℚ 𝔸]
    (x V y : 𝔸) : 𝔸 :=
  bchWordSum bchQuinticTermTaylor2Remainder4VCoeffs bchQuinticTermTaylor2Remainder4VWords x V y

/-- **Second-order Taylor remainder** of `bchQuinticTerm` in its first argument, split by the
number of `V` letters. The split is part of the definition, so the split identity is `rfl`. -/
noncomputable def bchQuinticTermTaylor2Remainder {𝔸 : Type*} [Ring 𝔸] [SMul ℚ 𝔸]
    (x V y : 𝔸) : 𝔸 :=
  bchQuinticTermTaylor2Remainder2V x V y + bchQuinticTermTaylor2Remainder3V x V y +
    bchQuinticTermTaylor2Remainder4V x V y

end

end FQFP.BCH
